[tool.poetry]
name = "booking"
version = "0.1.0"
description = ""
authors = ["Psychotim <balduev.desco@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.2"
ruff = "^0.2.1"
mypy = "^1.8.0"
uvicorn = "^0.27.1"

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 120
lint.select = ["ALL"]
lint.ignore = ["D1", "D203", "D213", "FA102", "ANN101", "UP007", "FA100", "COM812", "ISC001"]

[tool.ruff.lint.isort]
no-lines-before = ["standard-library", "local-folder"]
known-third-party = []
known-local-folder = ["whole_app"]
 
[tool.ruff.lint.extend-per-file-ignores]
"tests/*.py" = ["ANN401", "S101", "S311"]

[tool.pytest.ini_options]
pythonpath = [".", "src"]


[build-system]
requires = ["poetry-core>=1.7"]
build-backend = "poetry.core.masonry.api"