[api]
host = "0.0.0.0"
port = 5000
debug = false

[db]
host = "postgres"
port = 5432
database = "database"
user = "admin"
password = "admin"
echo = true

[logging]
level = "DEBUG"
render_json_logs = true
#path = "./logs/logs.log"
