name: UserService

on:
  workflow_call:

  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"
          cache: "poetry"
          cache-dependency-path: poetry.lock
      - name: Install dependencies
        run: poetry install --with lint, test
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"
          cache: "poetry"
          cache-dependency-path: poetry.lock
      - name: Lint with ruff & mypy
        run: |
          poetry run mypy . --explicit-package-bases 
          poetry ruff format
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"
          cache: "poetry"
          cache-dependency-path: poetry.lock
      - name: Test with pytest
        run: poetry run pytest
